name: Quick Journal Page Sort

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to use for release'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Zip output
        run: |
          mkdir quick-journal-page-sort
          mkdir quick-journal-page-sort/scripts
          mkdir quick-journal-page-sort/styles
          cp module.json ./quick-journal-page-sort/
          cp ./styles/styles.css ./quick-journal-page-sort/styles/
          cp ./scripts/main.js ./quick-journal-page-sort/scripts/
          zip -r quick-journal-page-sort.zip quick-journal-page-sort

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Handle both trigger types, github.event.inputs.tag is for getting the tag manual. If not found the automatic tag retrieval is used.
          # input events are only available for manual events aka workflow_dispatch events.
          tag="${{ github.event.inputs.tag || github.ref_name }}"
          
          gh release create "$tag" \
            --title="Release $tag" \
            --draft \
            module.json quick-journal-page-sort.zip
